### PR TITLE
github2spec -> repo2spec in README.md

### PR DESCRIPTION
**Pull request by piotr1212**

### CODE REVIEW

**Comment by ingvagabund** [comment]
Hi Piotr,

both forms are working. 'gofed github2spec' is a symlink to 'gofed repo2spec'. So you don't have to always type 'gofed repo2spec --github'.

Do you think 'gofed repo2spec --github' is better than the former?

**Comment by piotr1212** [comment]
Ah, I see now. I've installed gofed from updates-testing and run the command which failed. I assumed that the syntax was deprecated, but it seems that the symlinks are not made in the .spec file

**Comment by ingvagabund** [comment]
You are right. Some symlinks are not being copied to rpm. Fixed via 689c959790ffdf83d124ae159dce4ee0c49776c2.

**Comment by ingvagabund** [comment]
You can use the latest rawhide build [1].

[1] http://koji.fedoraproject.org/koji/taskinfo?taskID=10883270

**Comment by piotr1212** [comment]
Not sure why but it still doesn't work as supposed. Will try to figure it out later.

**Comment by ingvagabund** [comment]
With gofed-0.0.8-2.fc24.x86_64.rpm installed on virtual machine with F22:
$ gofed github2spec 
Repository missing
Project missing

Try to run:
$ file /usr/share/gofed/github2gospec

It should give you:
/usr/share/gofed/github2gospec: Python script, ASCII text executable

cp command copying symlinks is missing -d option so all symlinks are actually followed and their targets are copying instead of symlinks. Will make another with with -d option for symlinks.

**Comment by ingvagabund** [comment]
- -d option added via bb53d2408c803e85ec9007e6ea56cb8f7163a040
- new fedora build: http://koji.fedoraproject.org/koji/taskinfo?taskID=10892537

**Comment by piotr1212** [comment]
seems to work now, thanks

**Pull request closed without merging**
